/* eslint-disable @next/next/no-img-element */
"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type View = "region" | "dm" | "store";
type Row = { year:number; week:number; month:string; ceco:string; store:string; dm:string; region:string; fhw:number|null; lobby:number|null; ratio:number; source:string };
type HistoricalDm = { year:number; week:number; dm:string; ratio:number };
type Organization = { regions:number; dms:number; stores:number; hierarchy:Array<{name:string;dms:Array<{name:string;stores:Array<{ceco:string;name:string;applies?:boolean}>}>}> };
type Coverage = { week:number; publishedStores:number };
type Quality = { status:"ok"|"review"; latestCoverage:number };
type Payload = { meta:{ title:string; version:string; target:number; latestCompleteWeek:number; months:string[]; monthWeeks:Record<string,number[]>; historyFiles:Record<string,string>; organization:Organization; coverageByWeek:Coverage[]; quality:Quality }; records:Row[]; historicalDm:HistoricalDm[] };
type Resource = { id:string; category:string; title:string; description:string; file:string; action:string };
type ResourceConfig = { resources:Resource[] };
type Result = { id:string; label:string; detail:string; ratio:number; stores:number; direct:boolean };
type TrendPoint = { key:string; label:string; ratio:number; direct:boolean };

const pct = new Intl.NumberFormat("es-MX", { style:"percent", minimumFractionDigits:1, maximumFractionDigits:1 });
const LEVELS:View[] = ["region","dm","store"];
const labelView = (view:View) => view === "region" ? "Región" : view === "dm" ? "DM" : "Tienda";
const pluralView = (view:View) => view === "region" ? "Regiones" : view === "dm" ? "DMs" : "Tiendas";

function weighted(rows:Row[]) {
  const valid=rows.filter((row)=>row.fhw!==null&&row.lobby!==null&&row.lobby>0);
  const fhw=valid.reduce((sum,row)=>sum+(row.fhw??0),0), lobby=valid.reduce((sum,row)=>sum+(row.lobby??0),0);
  return { ratio:lobby?fhw/lobby:null };
}

function groupLive(rows:Row[],view:View):Result[] {
  const groups=new Map<string,Row[]>();
  rows.forEach((row)=>{const id=view==="store"?row.ceco:view==="dm"?row.dm:row.region;groups.set(id,[...(groups.get(id)??[]),row]);});
  return [...groups.entries()].map(([id,items])=>{const first=items[0],stores=new Set(items.map((item)=>item.ceco)).size;return{id,label:view==="store"?first.store:id,detail:view==="store"?`${first.dm} · ${first.region}`:view==="dm"?`${first.region} · ${stores} tiendas`:`${stores} tiendas`,ratio:weighted(items).ratio??0,stores,direct:false};});
}

function LevelIcon({view}:{view:View}) {
  if(view==="region")return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20V8l8-4 8 4v12M8 11h.01M12 11h.01M16 11h.01M8 15h.01M12 15h.01M16 15h.01M9 20v-2h6v2"/></svg>;
  if(view==="dm")return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M16 20v-1.5a3.5 3.5 0 0 0-3.5-3.5h-5A3.5 3.5 0 0 0 4 18.5V20M10 11a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7ZM16 11a3 3 0 0 0 0-6M18 15.5c1.2.5 2 1.6 2 3V20"/></svg>;
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 9h16l-1-5H5L4 9Zm1 0v11h14V9M9 20v-6h6v6M4 9c0 1.5 1 2.5 2.5 2.5S9 10.5 9 9c0 1.5 1 2.5 3 2.5S15 10.5 15 9c0 1.5 1 2.5 2.5 2.5S20 10.5 20 9"/></svg>;
}

function MultiSelect({label,options,selected,onChange,allLabel="Todos"}:{label:string;options:string[];selected:string[];onChange:(items:string[])=>void;allLabel?:string}) {
  const summary=selected.length===0?allLabel:selected.length===1?selected[0]:`${selected.length} seleccionados`;
  function toggle(item:string){onChange(selected.includes(item)?selected.filter((value)=>value!==item):[...selected,item]);}
  return <details className="multi-select"><summary><span>{label}</span><strong>{summary}</strong><svg viewBox="0 0 20 20" aria-hidden="true"><path d="m5 8 5 5 5-5"/></svg></summary><div className="multi-options"><label className="option-all"><input type="checkbox" checked={selected.length===0} onChange={()=>onChange([])}/><span>{allLabel}</span></label>{options.map((item)=><label key={item}><input type="checkbox" checked={selected.includes(item)} onChange={()=>toggle(item)}/><span>{item}</span></label>)}</div></details>;
}

function ScoreRing({value,target}:{value:number|null;target:number}) {
  const progress=value===null?0:Math.min(value/target,1);
  return <div className="score-ring"><svg viewBox="0 0 120 120" role="img" aria-label={value===null?"Sin resultado":pct.format(value)}><circle className="ring-track" cx="60" cy="60" r="48"/><circle className="ring-value" cx="60" cy="60" r="48" pathLength="1" strokeDasharray={`${progress} 1`}/></svg><span><strong>{value===null?"—":pct.format(value)}</strong><small>meta &gt; 10%</small></span></div>;
}

function TrendChart({points,target}:{points:TrendPoint[];target:number}) {
  if(!points.length)return <div className="empty"><strong>Sin tendencia disponible</strong><span>Ajusta el periodo o el alcance.</span></div>;
  const width=760,height=250,left=50,right=26,top=22,bottom=44,max=Math.max(target*1.3,...points.map((point)=>point.ratio*1.14),.02),min=Math.max(0,Math.min(...points.map((point)=>point.ratio),target)*.72);
  const x=(index:number)=>points.length===1?width/2:left+index*((width-left-right)/(points.length-1)),y=(value:number)=>top+(max-value)*((height-top-bottom)/(max-min));
  return <svg className="trend-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Evolución de Cada Taza Cuenta">{[min,(min+max)/2,max].map((value)=><g key={value}><line x1={left} x2={width-right} y1={y(value)} y2={y(value)} className="chart-grid"/><text x={left-10} y={y(value)+4} textAnchor="end">{pct.format(value)}</text></g>)}<line x1={left} x2={width-right} y1={y(target)} y2={y(target)} className="chart-target"/><text x={width-right} y={y(target)-8} textAnchor="end" className="target-copy">Objetivo 10%</text><polyline points={points.map((point,index)=>`${x(index)},${y(point.ratio)}`).join(" ")} className="chart-line"/>{points.map((point,index)=><g className="chart-point" key={point.key}><circle cx={x(index)} cy={y(point.ratio)} r="6" className={point.ratio>target?"is-good":""}/><text x={x(index)} y={height-17} textAnchor="middle">{point.label}</text><title>{`${point.label}: ${pct.format(point.ratio)}`}</title></g>)}</svg>;
}

function Ranking({items,target,onSelect}:{items:Result[];target:number;onSelect:(item:Result)=>void}) {
  const max=Math.max(...items.map((item)=>item.ratio),target,.01);
  return <div className="ranking-list">{items.map((item,index)=><button key={item.id} onClick={()=>onSelect(item)}><span className="rank-number">{index+1}</span><span className="rank-name"><strong>{item.label}</strong><small>{item.detail}</small></span><span className="rank-line"><i className={item.ratio>target?"is-good":""} style={{width:`${Math.max(3,item.ratio/max*100)}%`}}/></span><strong className="rank-score">{pct.format(item.ratio)}</strong></button>)}</div>;
}

export default function Dashboard(){
  const [data,setData]=useState<Payload|null>(null),[resources,setResources]=useState<ResourceConfig>({resources:[]}),[error,setError]=useState("");
  const [view,setView]=useState<View>("region"),[month,setMonth]=useState(""),[week,setWeek]=useState(0),[regionsSelected,setRegionsSelected]=useState<string[]>([]),[dmsSelected,setDmsSelected]=useState<string[]>([]),[query,setQuery]=useState("");
  const [trendMode,setTrendMode]=useState<"week"|"month">("week"),[rankingMode,setRankingMode]=useState<"top"|"bottom">("top"),[sortMode,setSortMode]=useState<"ratio-desc"|"ratio-asc"|"name">("ratio-desc");
  const [historyRows,setHistoryRows]=useState<Row[]>([]),[historyDm,setHistoryDm]=useState<HistoricalDm[]>([]),[historyLoading,setHistoryLoading]=useState(false),[historyError,setHistoryError]=useState("");
  const historyRequested=useRef(new Set<string>()),urlReady=useRef(false);

  useEffect(()=>{Promise.all([fetch("data/fhw-dashboard.json").then((response)=>{if(!response.ok)throw new Error("No se pudo leer la base");return response.json();}),fetch("data/resources.json").then((response)=>response.json())]).then(([payload,resourcePayload]:[Payload,ResourceConfig])=>{setData(payload);setResources(resourcePayload);const params=new URLSearchParams(location.search),latest=payload.meta.latestCompleteWeek,latestMonth=payload.records.find((row)=>row.week===latest)?.month??payload.meta.months.at(-1)??"",requestedMonth=params.get("mes"),nextMonth=requestedMonth&&payload.meta.months.includes(requestedMonth)?requestedMonth:latestMonth,weeks=payload.meta.monthWeeks[nextMonth]??[],requestedWeek=Number(params.get("semana")),requestedView=params.get("vista"),regionParam=params.get("regiones")??params.get("region")??"",dmParam=params.get("dms")??params.get("dm")??"";setMonth(nextMonth);setWeek(weeks.includes(requestedWeek)?requestedWeek:weeks.at(-1)??latest);setView(requestedView&&LEVELS.includes(requestedView as View)?requestedView as View:"region");setRegionsSelected(regionParam.split("|").filter((item)=>item&&item!=="Todas"));setDmsSelected(dmParam.split("|").filter((item)=>item&&item!=="Todos"));setQuery(params.get("q")??"");setTrendMode(params.get("tendencia")==="month"?"month":"week");urlReady.current=true;}).catch((reason)=>setError(reason instanceof Error?reason.message:"No se pudo cargar el tablero"));},[]);
  useEffect(()=>{if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js").catch(()=>undefined);},[]);
  useEffect(()=>{if(!data||!month)return;const targets=trendMode==="month"?Object.keys(data.meta.historyFiles):[month],pending=targets.filter((item)=>data.meta.historyFiles[item]&&!historyRequested.current.has(item));if(!pending.length)return;pending.forEach((item)=>historyRequested.current.add(item));queueMicrotask(()=>setHistoryLoading(true));Promise.all(pending.map(async(item)=>{const response=await fetch(data.meta.historyFiles[item]);if(!response.ok)throw new Error(`No se pudo leer ${item}`);return response.json() as Promise<{records:Row[];historicalDm:HistoricalDm[]}>;})).then((items)=>{setHistoryRows((current)=>[...current,...items.flatMap((item)=>item.records)]);setHistoryDm((current)=>[...current,...items.flatMap((item)=>item.historicalDm)]);setHistoryError("");}).catch((reason)=>{pending.forEach((item)=>historyRequested.current.delete(item));setHistoryError(reason instanceof Error?reason.message:"Histórico parcial");}).finally(()=>setHistoryLoading(false));},[data,month,trendMode]);
  useEffect(()=>{if(!data||!urlReady.current)return;const params=new URLSearchParams({vista:view,mes:month,semana:String(week)});if(regionsSelected.length)params.set("regiones",regionsSelected.join("|"));if(dmsSelected.length)params.set("dms",dmsSelected.join("|"));if(query)params.set("q",query);if(trendMode==="month")params.set("tendencia","month");history.replaceState(null,"",`${location.pathname}?${params}`);},[data,view,month,week,regionsSelected,dmsSelected,query,trendMode]);

  const baseRows=useMemo(()=>[...(data?.records??[]),...historyRows],[data,historyRows]),allHistoricalDm=useMemo(()=>[...(data?.historicalDm??[]),...historyDm],[data,historyDm]);
  const regionOptions=useMemo(()=>data?.meta.organization.hierarchy.map((item)=>item.name)??[],[data]);
  const dmOptions=useMemo(()=>{const hierarchy=data?.meta.organization.hierarchy??[],scope=regionsSelected.length?hierarchy.filter((item)=>regionsSelected.includes(item.name)):hierarchy;return [...new Set(scope.flatMap((item)=>item.dms.map((district)=>district.name)))].sort((a,b)=>a.localeCompare(b,"es"));},[data,regionsSelected]);
  const monthWeeks=useMemo(()=>data?.meta.monthWeeks[month]??[],[data,month]);
  const hierarchyRows=useMemo(()=>{const term=query.trim().toLocaleLowerCase("es-MX");return baseRows.filter((row)=>(!regionsSelected.length||regionsSelected.includes(row.region))&&(!dmsSelected.length||dmsSelected.includes(row.dm))&&(!term||row.store.toLocaleLowerCase("es-MX").includes(term)||row.ceco.includes(term)));},[baseRows,regionsSelected,dmsSelected,query]);
  const periodRows=hierarchyRows.filter((row)=>row.week===week),hasLive=periodRows.some((row)=>row.fhw!==null&&row.lobby!==null);
  const results:Result[]=(()=>{if(!data)return[];if(hasLive)return groupLive(periodRows.filter((row)=>row.fhw!==null&&row.lobby!==null),view);if(view==="store")return periodRows.map((row)=>({id:row.ceco,label:row.store,detail:`${row.dm} · ${row.region}`,ratio:row.ratio,stores:1,direct:true}));if(view==="dm"){const allowed=new Set(periodRows.map((row)=>row.dm));return allHistoricalDm.filter((item)=>item.week===week&&allowed.has(item.dm)).map((item)=>({id:item.dm,label:item.dm,detail:"Cierre histórico",ratio:item.ratio,stores:0,direct:true}));}return[];})();
  const score=hasLive?weighted(periodRows).ratio:results.length===1?results[0].ratio:null,atTarget=results.filter((item)=>item.ratio>(data?.meta.target??.1)).length,coverage=data?.meta.coverageByWeek.find((item)=>item.week===week);
  const sorted=[...results].sort((a,b)=>sortMode==="name"?a.label.localeCompare(b.label,"es"):sortMode==="ratio-desc"?b.ratio-a.ratio:a.ratio-b.ratio),ranked=[...results].sort((a,b)=>rankingMode==="top"?b.ratio-a.ratio:a.ratio-b.ratio).slice(0,8);

  const trend:TrendPoint[]=(()=>{if(!data)return[];if(trendMode==="week"){const rows=hierarchyRows.filter((row)=>row.month===month),weeks=[...new Set(rows.map((row)=>row.week))].sort((a,b)=>a-b),oneStore=view==="store"&&new Set(rows.map((row)=>row.ceco)).size===1;return weeks.map((item)=>{const cut=rows.filter((row)=>row.week===item),live=weighted(cut);if(live.ratio!==null)return{key:`w${item}`,label:`S${item}`,ratio:live.ratio,direct:false};if(oneStore&&cut[0])return{key:`w${item}`,label:`S${item}`,ratio:cut[0].ratio,direct:true};if(view==="dm"&&dmsSelected.length===1){const direct=allHistoricalDm.find((row)=>row.week===item&&row.dm===dmsSelected[0]);if(direct)return{key:`w${item}`,label:`S${item}`,ratio:direct.ratio,direct:true};}return null;}).filter((item):item is TrendPoint=>item!==null);}const months=data.meta.months;return months.map((item)=>{const cut=hierarchyRows.filter((row)=>row.month===item),live=weighted(cut);if(live.ratio!==null)return{key:item,label:item,ratio:live.ratio,direct:false};if(view==="store"&&new Set(cut.map((row)=>row.ceco)).size===1&&cut.length){const close=[...cut].sort((a,b)=>b.week-a.week)[0];return{key:item,label:item,ratio:close.ratio,direct:true};}if(view==="dm"&&dmsSelected.length===1){const weeks=data.meta.monthWeeks[item]??[],close=allHistoricalDm.filter((row)=>weeks.includes(row.week)&&row.dm===dmsSelected[0]).sort((a,b)=>b.week-a.week)[0];if(close)return{key:item,label:item,ratio:close.ratio,direct:true};}return null;}).filter((item):item is TrendPoint=>item!==null);})();
  const currentPoint=trendMode==="week"?trend.find((item)=>item.key===`w${week}`):trend.at(-1),previous=currentPoint?trend[trend.indexOf(currentPoint)-1]:undefined,delta=currentPoint&&previous?currentPoint.ratio-previous.ratio:null,priority=[...results].sort((a,b)=>a.ratio-b.ratio)[0],scopeLabel=dmsSelected.length?dmsSelected.join(", "):regionsSelected.length?regionsSelected.join(", "):"Nacional";
  const storyTitle=score===null?"Selecciona un corte con información":score>data.meta.target?"El alcance supera el objetivo":"La oportunidad está identificada";
  const storyText=score===null?"La historia aparece al elegir un periodo ponderable.":`${atTarget} de ${results.length} ${pluralView(view).toLocaleLowerCase("es-MX")} están sobre 10%.${priority?` ${priority.label} concentra la siguiente conversación.`:""}`;

  function changeMonth(value:string){setMonth(value);setWeek((data?.meta.monthWeeks[value]??[]).at(-1)??0);}
  function selectRegions(items:string[]){setRegionsSelected(items);setDmsSelected([]);setQuery("");setView(items.length?"dm":"region");setRankingMode("top");}
  function selectDms(items:string[]){setDmsSelected(items);setQuery("");setView(items.length?"store":"dm");setRankingMode("top");}
  function changeLevel(level:View){setView(level);setRankingMode("top");if(level==="region"){setRegionsSelected([]);setDmsSelected([]);setQuery("");}if(level==="dm"){setDmsSelected([]);setQuery("");}}
  function drillDown(item:Result){if(view==="region")selectRegions([item.id]);else if(view==="dm")selectDms([item.id]);else setQuery(item.label);document.querySelector(".story-card-v2")?.scrollIntoView({behavior:"smooth",block:"center"});}
  function reset(){setRegionsSelected([]);setDmsSelected([]);setQuery("");setView("region");setRankingMode("top");}
  function exportPdf(){const previous=document.title,level=pluralView(view),scope=scopeLabel.replaceAll(" ","_");document.title=`FHW_${level}_${scope}_S${week}`;document.body.dataset.exporting="true";const restore=()=>{document.title=previous;delete document.body.dataset.exporting;};window.addEventListener("afterprint",restore,{once:true});requestAnimationFrame(()=>window.print());window.setTimeout(restore,4000);}

  if(error)return <main className="state-screen"><img src="assets/logo-cada-taza-cuenta.webp" alt="FHW"/><h1>No pudimos abrir el tablero</h1><p>{error}</p><button onClick={()=>location.reload()}>Reintentar</button></main>;
  if(!data)return <main className="state-screen"><div className="loader"/><h1>Preparando Cada Taza Cuenta</h1><p>Validando el corte…</p></main>;

  const resource=resources.resources[0];
  return <div className="app-shell"><header className="topbar"><a className="brand" href="#inicio"><img src="assets/logo-cada-taza-cuenta.webp" alt="FHW"/><span><strong>FHW</strong><small>Cada Taza Cuenta</small></span></a><div className="header-actions"><span className="status-dot">Datos validados · S{data.meta.latestCompleteWeek}</span><button className="button export" onClick={exportPdf}>Exportar {pluralView(view)}</button></div></header>
    <main id="inicio"><section className="overview-card"><div className="overview-title"><h1>Cada Taza Cuenta</h1><p>{scopeLabel} · Semana {week}</p></div><ScoreRing value={score} target={data.meta.target}/><div className="overview-facts"><span><small>Movimiento</small><strong className={delta!==null&&delta>=0?"positive":""}>{delta===null?"—":`${delta>=0?"+":""}${pct.format(delta)}`}</strong></span><span><small>Cobertura</small><strong>{coverage?pct.format(coverage.publishedStores/data.meta.organization.stores):"—"}</strong></span><span><small>Sobre meta</small><strong>{atTarget} / {results.length}</strong></span></div></section>
      <section className="filter-card"><div className="level-tabs" role="tablist" aria-label="Nivel de análisis">{LEVELS.map((item,index)=><button key={item} role="tab" aria-selected={view===item} className={view===item?"active":""} onClick={()=>changeLevel(item)}><span>{index+1}</span><LevelIcon view={item}/><strong>{labelView(item)}</strong><small>{item==="region"?"Vista nacional":item==="dm"?"Por responsable":"Detalle operativo"}</small></button>)}</div><div className="filter-grid"><label className="native-filter"><span>Mes</span><select value={month} onChange={(event)=>changeMonth(event.target.value)}>{data.meta.months.map((item)=><option key={item}>{item}</option>)}</select></label><label className="native-filter"><span>Semana</span><select value={week} onChange={(event)=>setWeek(Number(event.target.value))}>{monthWeeks.map((item)=><option key={item} value={item}>S{item}</option>)}</select></label><MultiSelect label="Región" options={regionOptions} selected={regionsSelected} onChange={selectRegions} allLabel="Todas las regiones"/><MultiSelect label="DM" options={dmOptions} selected={dmsSelected} onChange={selectDms} allLabel="Todos los DMs"/>{view==="store"&&<label className="native-filter search-filter"><span>Tienda</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Nombre o CeCo"/></label>}</div><div className="scope-row"><span>{scopeLabel}</span><span>›</span><strong>{pluralView(view)}</strong>{(regionsSelected.length>0||dmsSelected.length>0||query)&&<button onClick={reset}>Restablecer</button>}</div></section>
      <section className="story-card-v2"><span className={score!==null&&score>data.meta.target?"story-signal good":"story-signal"}/><div><small>LECTURA DEL CORTE</small><h2>{storyTitle}</h2><p>{storyText}</p></div><div className="story-focus"><small>Siguiente foco</small><strong>{priority?.label??"Sin dato"}</strong><span>{priority?pct.format(priority.ratio):"—"}</span></div></section>
      <section className="dashboard-grid"><article className="panel trend-panel"><div className="panel-head"><div><small>TENDENCIA</small><h2>{trendMode==="week"?`Semana a semana · ${month}`:"Evolución mensual"}</h2></div><div className="toggle"><button className={trendMode==="week"?"active":""} onClick={()=>setTrendMode("week")}>Semanas</button><button className={trendMode==="month"?"active":""} onClick={()=>setTrendMode("month")}>Meses</button></div></div><TrendChart points={trend} target={data.meta.target}/>{historyLoading&&<span className="chart-note">Cargando historia…</span>}{historyError&&<span className="chart-note error">{historyError}</span>}<div className="chart-legend"><span><i/>Ponderado</span><span><i className="direct"/>Cierre histórico</span></div></article><article className="panel ranking-panel"><div className="panel-head"><div><small>RANKING · {pluralView(view).toUpperCase()}</small><h2>{rankingMode==="top"?"Mayor desempeño":"Mayor oportunidad"}</h2></div><div className="toggle"><button className={rankingMode==="top"?"active":""} onClick={()=>setRankingMode("top")}>Top</button><button className={rankingMode==="bottom"?"active":""} onClick={()=>setRankingMode("bottom")}>Bottom</button></div></div>{ranked.length?<Ranking items={ranked} target={data.meta.target} onSelect={drillDown}/>:<div className="empty"><strong>Sin datos en este corte</strong><span>Cambia la semana.</span></div>}</article></section>
      <section className="panel table-panel"><div className="panel-head"><div><small>DATA COMPLETA</small><h2>{pluralView(view)} · Semana {week}</h2></div><div className="table-tools"><span>{results.length} resultados</span><select value={sortMode} onChange={(event)=>setSortMode(event.target.value as typeof sortMode)} aria-label="Ordenar resultados"><option value="ratio-desc">Mayor a menor</option><option value="ratio-asc">Menor a mayor</option><option value="name">Nombre A–Z</option></select></div></div><div className="table-wrap"><table><thead><tr><th>Nombre</th><th>Cada Taza Cuenta</th><th>Estado</th></tr></thead><tbody>{sorted.map((item)=><tr key={item.id}><td><strong>{item.label}</strong><small>{item.detail}</small></td><td><strong>{pct.format(item.ratio)}</strong></td><td><span className={item.ratio>data.meta.target?"status good":"status opportunity"}>{item.ratio>data.meta.target?"Sobre meta":"Oportunidad"}</span></td></tr>)}</tbody></table></div></section>
      {resource&&<section className="resource-card"><div className="resource-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 3h9l3 3v15H6V3Zm8 0v4h4M9 12h6M9 16h6"/></svg></div><div><small>{resource.category}</small><h2>{resource.title}</h2><p>{resource.description}</p></div><a className="button solid" href={resource.file} download>{resource.action}</a></section>}
    </main><footer><div><strong>FHW · Cada Taza Cuenta</strong><span>Jesus Alfredo Lopez Ramirez · Especialista de Sustentabilidad &amp; Enrique César Flores · Gerente de Distrito</span></div><div><span>Información propiedad de la marca. Prohibida su divulgación.</span><a href="https://wa.me/message/ENKDSAHYHIGAN1" target="_blank" rel="noreferrer">Comentarios y/o Sugerencias</a></div></footer></div>;
}
