/* eslint-disable @next/next/no-img-element */
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { downloadDashboardPdf } from "./pdf-report";
import { downloadDashboardXlsx } from "./xlsx-report";

type View = "region" | "dm" | "store";
type Row = { year: number; week: number; month: string; ceco: string; store: string; dm: string; region: string; fhw: number | null; lobby: number | null; ratio: number; source: string };
type Organization = { hierarchy: Array<{ name: string; dms: Array<{ name: string; stores: Array<{ ceco: string; name: string; applies?: boolean }> }> }> };
type Payload = { meta: { target: number; latestCompleteWeek: number; weeks: number[]; months: string[]; monthWeeks: Record<string, number[]>; historyFiles: Record<string, string>; organization: Organization }; records: Row[] };
type Resource = { id: string; category: string; title: string; description: string; file: string; action: string };
type ResourceConfig = { resources: Resource[] };
type Initiative = { eyebrow: string; title: string; message: string; closing: string; badge: string };
type Result = { id: string; label: string; detail: string; ratio: number; stores: number };
type TrendPoint = { key: string; label: string; ratio: number };
type ExportKind = "pdf" | "xlsx";

const pct = new Intl.NumberFormat("es-MX", { style: "percent", minimumFractionDigits: 1, maximumFractionDigits: 1 });
const LEVELS: View[] = ["region", "dm", "store"];
const labelView = (view: View) => view === "region" ? "Región" : view === "dm" ? "DM" : "Tienda";
const pluralView = (view: View) => view === "region" ? "Regiones" : view === "dm" ? "DMs" : "Tiendas";
const displayDm = (value: string) => value.toLocaleLowerCase("es-MX") === "vacante" ? "DM por asignar" : value;
const conciseRange = (weeks: number[]) => { const ordered = [...weeks].sort((a, b) => a - b); return !ordered.length ? "Sin semanas" : ordered.length === 1 ? `S${ordered[0]}` : ordered.length === 2 ? `S${ordered[0]}–S${ordered[1]}` : `Inicio S${ordered[0]} · Fin S${ordered.at(-1)}`; };
const periodRange = (months: string[]) => months.length < 2 ? (months[0] ?? "Sin datos") : `${months[0]}–${months.at(-1)}`;
const conciseMonths = (months: string[]) => !months.length ? "Sin datos" : months.length === 1 ? months[0] : months.length <= 3 ? months.join(" · ") : `${months.length} meses`;

function average(rows: Row[]) { const valid = rows.filter((row) => Number.isFinite(row.ratio) && row.ratio >= 0 && row.ratio <= 1); return { ratio: valid.length ? valid.reduce((sum, row) => sum + row.ratio, 0) / valid.length : null, stores: new Set(valid.map((row) => row.ceco)).size }; }
function adoption(rows: Row[]) { const latest = new Map<string, Row>(); rows.forEach((row) => latest.set(row.ceco, row)); const items = [...latest.values()]; return { above: items.filter((row) => row.ratio > .1).length, stores: items.length }; }
function group(rows: Row[], view: View): Result[] { const groups = new Map<string, Row[]>(); rows.forEach((row) => { const id = view === "store" ? row.ceco : view === "dm" ? row.dm : row.region; groups.set(id, [...(groups.get(id) ?? []), row]); }); return [...groups.entries()].map(([id, items]) => { const first = items[0], stores = new Set(items.map((item) => item.ceco)).size, score = average(items).ratio; return { id, label: view === "store" ? `${first.store} · ${first.ceco}` : view === "dm" ? displayDm(id) : id, detail: view === "store" ? `${displayDm(first.dm)} · ${first.region}` : view === "dm" ? `${first.region} · ${stores} tiendas` : `${stores} tiendas`, ratio: score ?? 0, stores }; }); }

function ScoreRing({ value }: { value: number | null }) { const progress = value === null ? 0 : Math.min(value / .1, 1); return <div className="score-ring"><svg viewBox="0 0 120 120" role="img" aria-label={value === null ? "Sin resultado" : pct.format(value)}><circle className="ring-track" cx="60" cy="60" r="48"/><circle className="ring-value" cx="60" cy="60" r="48" pathLength="1" strokeDasharray={`${progress} 1`}/></svg><span><strong>{value === null ? "—" : pct.format(value)}</strong><small>promedio CTC</small></span></div>; }

function TrendChart({ points, target }: { points: TrendPoint[]; target: number | null }) {
  if (!points.length) return <div className="empty"><strong>Sin datos para este corte</strong><span>No hay información disponible.</span></div>;
  const width = 820, height = 250, left = 50, right = 24, top = 24, bottom = 44, observed = Math.max(...points.map((point) => point.ratio), target ?? 0, .02), max = Math.min(1, Math.max(observed * 1.14, target ? target * 1.3 : 0)), min = Math.max(0, Math.min(...points.map((point) => point.ratio), target ?? 1) * .72), step = Math.max(1, Math.ceil(points.length / 10));
  const x = (index: number) => points.length === 1 ? width / 2 : left + index * ((width - left - right) / (points.length - 1));
  const y = (value: number) => top + (max - value) * ((height - top - bottom) / (max - min || 1));
  return <svg className="trend-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Tendencia promedio de Cada Taza Cuenta">{[min, (min + max) / 2, max].map((value) => <g key={value}><line x1={left} x2={width - right} y1={y(value)} y2={y(value)} className="chart-grid"/><text x={left - 10} y={y(value) + 4} textAnchor="end">{pct.format(value)}</text></g>)}{target !== null && <><line x1={left} x2={width - right} y1={y(target)} y2={y(target)} className="chart-target"/><text x={width - right} y={y(target) - 8} textAnchor="end" className="target-copy">Objetivo 10%</text></>}<polyline points={points.map((point, index) => `${x(index)},${y(point.ratio)}`).join(" ")} className="chart-line"/>{points.map((point, index) => <g className="chart-point" key={point.key}><circle cx={x(index)} cy={y(point.ratio)} r={points.length > 16 ? 4 : 6}/>{(index % step === 0 || index === points.length - 1) && <text x={x(index)} y={height - 17} textAnchor="middle">{point.label}</text>}<title>{`${point.label}: ${pct.format(point.ratio)}`}</title></g>)}</svg>;
}

function Ranking({ items, onSelect, compact = false }: { items: Result[]; onSelect: (item: Result) => void; compact?: boolean }) { const max = Math.max(...items.map((item) => item.ratio), .01); return <div className={compact ? "ranking-list compact-grid" : "ranking-list"}>{items.map((item, index) => <button key={item.id} onClick={() => onSelect(item)}><span className="rank-number">{index + 1}</span><span className="rank-name"><strong>{item.label}</strong><small>{item.detail}</small></span><span className="rank-line"><i style={{ width: `${Math.max(3, item.ratio / max * 100)}%` }}/></span><strong className="rank-score">{pct.format(item.ratio)}</strong></button>)}</div>; }

function ExportDialog({ kind, complete, onCancel, onConfirm }: { kind: ExportKind | null; complete: ExportKind | null; onCancel: () => void; onConfirm: () => void }) { if (!kind && !complete) return null; const current = complete ?? kind, isPdf = current === "pdf"; return <div className="export-dialog" role="dialog" aria-modal="true" aria-labelledby="export-title"><div className="export-dialog-card"><button className="dialog-close" onClick={onCancel} aria-label="Cerrar">×</button><img src={complete ? "assets/un-placer-haber-ayudado.webp" : "assets/damos-seguimiento.webp"} alt=""/><div><small>{complete ? "EXPORTACIÓN LISTA" : "VALIDAR EXPORTACIÓN"}</small><h2 id="export-title">{complete ? "Un placer haber ayudado" : "Revisa tu selección"}</h2><p>{complete ? (isPdf ? "El PDF ejecutivo horizontal ya se descargó en tu dispositivo." : "El Excel Dashboard ya se descargó con resumen, detalle y tendencia.") : (isPdf ? "Descargarás un PDF horizontal de una hoja con el alcance, tendencia y prioridades del filtro actual." : "Descargarás un Excel Dashboard con resumen ejecutivo, detalle filtrado y tendencia.")}</p><div className="export-dialog-actions">{!complete && <button className="button solid" onClick={onConfirm}>{isPdf ? "Descargar PDF" : "Descargar Excel"}</button>}<button className="button quiet" onClick={onCancel}>{complete ? "Cerrar" : "Cancelar"}</button></div></div></div></div>; }

export default function Dashboard() {
  const [data, setData] = useState<Payload | null>(null), [resources, setResources] = useState<ResourceConfig>({ resources: [] }), [initiative, setInitiative] = useState<Initiative | null>(null), [error, setError] = useState("");
  const [view, setView] = useState<View>("region"), [region, setRegion] = useState(""), [dm, setDm] = useState(""), [storeSearch, setStoreSearch] = useState(""), [selectedMonths, setSelectedMonths] = useState<string[]>([]), [selectedWeeks, setSelectedWeeks] = useState<number[]>([]), [trendPeriod, setTrendPeriod] = useState<"week" | "month">("month"), [rankingMode, setRankingMode] = useState<"top" | "bottom">("top");
  const [exportIntent, setExportIntent] = useState<ExportKind | null>(null), [exportComplete, setExportComplete] = useState<ExportKind | null>(null), [historyRows, setHistoryRows] = useState<Row[]>([]), [historyLoading, setHistoryLoading] = useState(false), [historyError, setHistoryError] = useState("");
  const historyRequested = useRef(new Set<string>()), exportRef = useRef<HTMLDetailsElement>(null);

  useEffect(() => { Promise.all([fetch("data/fhw-dashboard.json").then((response) => { if (!response.ok) throw new Error("No se pudo leer la base"); return response.json(); }), fetch("data/resources.json").then((response) => response.json()), fetch("data/juntemonos-mas.json").then((response) => response.json())]).then(([payload, resourcePayload, initiativePayload]: [Payload, ResourceConfig, Initiative]) => { setData(payload); setResources(resourcePayload); setInitiative(initiativePayload); const params = new URLSearchParams(location.search), requestedView = params.get("vista") as View | null, requestedMonths = (params.get("meses") ?? "").split(",").filter((month) => payload.meta.months.includes(month)), requestedWeeks = (params.get("semanas") ?? "").split(",").map(Number).filter((week) => payload.meta.weeks.includes(week)); setView(requestedView && LEVELS.includes(requestedView) ? requestedView : "region"); setRegion(params.get("region") ?? ""); setDm(params.get("dm") ?? ""); setSelectedMonths([...new Set(requestedMonths)]); setSelectedWeeks([...new Set(requestedWeeks)].sort((a, b) => a - b)); setTrendPeriod(params.get("periodo") === "week" ? "week" : "month"); }).catch((reason) => setError(reason instanceof Error ? reason.message : "No se pudo cargar el tablero")); }, []);
  useEffect(() => { if ("serviceWorker" in navigator) navigator.serviceWorker.getRegistrations().then((registrations) => Promise.all(registrations.map((registration) => registration.unregister()))).catch(() => undefined); }, []);
  useEffect(() => { if (!data) return; const pending = data.meta.months.filter((month) => data.meta.historyFiles[month] && !historyRequested.current.has(month)); if (!pending.length) return; pending.forEach((month) => historyRequested.current.add(month)); queueMicrotask(() => setHistoryLoading(true)); Promise.all(pending.map(async (month) => { const response = await fetch(data.meta.historyFiles[month]); if (!response.ok) throw new Error(`No se pudo leer ${month}`); return response.json() as Promise<{ records: Row[] }>; })).then((items) => { setHistoryRows((current) => [...current, ...items.flatMap((item) => item.records)]); setHistoryError(""); }).catch((reason) => { pending.forEach((month) => historyRequested.current.delete(month)); setHistoryError(reason instanceof Error ? reason.message : "Histórico parcial"); }).finally(() => setHistoryLoading(false)); }, [data]);
  useEffect(() => { if (!data) return; const params = new URLSearchParams({ vista: view }); if (region) params.set("region", region); if (dm) params.set("dm", dm); if (selectedMonths.length) params.set("meses", selectedMonths.join(",")); if (selectedWeeks.length) params.set("semanas", selectedWeeks.join(",")); if (trendPeriod === "week") params.set("periodo", "week"); history.replaceState(null, "", `${location.pathname}?${params}`); }, [data, view, region, dm, selectedMonths, selectedWeeks, trendPeriod]);

  const allRows = useMemo(() => [...(data?.records ?? []), ...historyRows], [data, historyRows]);
  const regionOptions = useMemo(() => data?.meta.organization.hierarchy.map((item) => item.name) ?? [], [data]);
  const dmOptions = useMemo(() => { const hierarchy = data?.meta.organization.hierarchy ?? [], scope = region ? hierarchy.filter((item) => item.name === region) : hierarchy; return [...new Set(scope.flatMap((item) => item.dms.map((district) => district.name)))].sort((a, b) => displayDm(a).localeCompare(displayDm(b), "es")); }, [data, region]);
  const availableWeeks = useMemo(() => { const weeks = data?.meta.weeks ?? []; if (!data || !selectedMonths.length) return weeks; const allowed = new Set(selectedMonths.flatMap((month) => data.meta.monthWeeks[month] ?? [])); return weeks.filter((week) => allowed.has(week)); }, [data, selectedMonths]);
  const activeWeeks = selectedWeeks.length ? availableWeeks.filter((week) => selectedWeeks.includes(week)) : availableWeeks, activeMonths = useMemo(() => { if (!data) return []; return data.meta.months.filter((month) => (data.meta.monthWeeks[month] ?? []).some((week) => activeWeeks.includes(week))); }, [data, activeWeeks]), latestCutWeek = activeWeeks.at(-1) ?? data?.meta.latestCompleteWeek ?? 0;
  const scopeRows = useMemo(() => allRows.filter((row) => (!region || row.region === region) && (!dm || row.dm === dm)), [allRows, region, dm]);
  const baseSelectedRows = scopeRows.filter((row) => activeWeeks.includes(row.week) && activeMonths.includes(row.month)), searchKey = storeSearch.trim().toLocaleLowerCase("es-MX"), selectedRows = view === "store" && searchKey ? baseSelectedRows.filter((row) => `${row.store} ${row.ceco}`.toLocaleLowerCase("es-MX").includes(searchKey)) : baseSelectedRows, latestRows = selectedRows.filter((row) => row.week === latestCutWeek);
  const results = group(selectedRows, view), score = average(selectedRows).ratio, storeStatus = adoption(latestRows), scopeStores = new Set(scopeRows.map((row) => row.ceco)).size, coverageRatio = scopeStores ? new Set(latestRows.map((row) => row.ceco)).size / scopeStores : null;
  const rankingLimit = view === "region" ? 11 : view === "dm" ? 9 : 10, sortedResults = [...results].sort((a, b) => b.ratio - a.ratio), ranked = (rankingMode === "top" ? sortedResults : [...sortedResults].reverse()).slice(0, rankingLimit), priority = [...results].sort((a, b) => a.ratio - b.ratio)[0], leader = sortedResults[0], isNational = view === "region" && !region && !dm, pdfLimit = isNational ? 11 : view === "dm" ? 5 : 3;
  const periodLabel = selectedMonths.length || selectedWeeks.length ? conciseMonths(activeMonths) : periodRange(data?.meta.months ?? []), rangeLabel = conciseRange(activeWeeks), scopeLabel = dm ? displayDm(dm) : region || "Nacional", scopeHeading = storeSearch.trim() ? `Tienda · ${storeSearch.trim()}` : dm ? `${displayDm(dm)} · Tiendas` : region ? `${region} · ${view === "dm" ? "DMs" : "Tiendas"}` : view === "region" ? "Nacional" : `Nacional · ${pluralView(view)}`, metricLabel = `Promedio por ${labelView(view)}`, trendTitle = `Promedio Cada Taza Cuenta · ${scopeHeading}`;
  const trend: TrendPoint[] = (() => { if (!data) return []; if (trendPeriod === "week") return activeWeeks.flatMap((week) => { const ratio = average(selectedRows.filter((row) => row.week === week)).ratio; return ratio === null ? [] : [{ key: `w${week}`, label: `S${week}`, ratio }]; }); return activeMonths.flatMap((month) => { const monthWeeks = data.meta.monthWeeks[month] ?? [], ratio = average(selectedRows.filter((row) => monthWeeks.includes(row.week) && activeWeeks.includes(row.week))).ratio; return ratio === null ? [] : [{ key: month, label: month, ratio }]; }); })();
  const scoreTrend = activeWeeks.flatMap((week) => { const ratio = average(selectedRows.filter((row) => row.week === week)).ratio; return ratio === null ? [] : [{ week, ratio }]; }), previous = scoreTrend.at(-2), current = scoreTrend.at(-1), delta = current && previous ? current.ratio - previous.ratio : null;
  const storyTitle = score === null ? "Sin información en este corte" : score > .1 ? "El avance supera el objetivo" : "La oportunidad está localizada", storyText = score === null ? "No hay información disponible para este alcance." : `Promedio CTC: ${pct.format(score)}.${delta !== null ? ` Movimiento ${delta >= 0 ? "+" : ""}${pct.format(delta)} vs sem. anterior.` : ""}${priority ? ` ${priority.label} es el siguiente foco.` : ""}`;

  function selectRegion(value: string) { setRegion(value); setDm(""); setStoreSearch(""); setView(value ? "dm" : "region"); setRankingMode("top"); }
  function selectDm(value: string) { setDm(value); setStoreSearch(""); setView(value ? "store" : "dm"); setRankingMode("top"); }
  function changeLevel(level: View) { setView(level); setStoreSearch(""); setRankingMode("top"); if (level === "region") { setRegion(""); setDm(""); } else if (level === "dm") setDm(""); }
  function toggleMonth(month: string) { const nextMonths = selectedMonths.includes(month) ? selectedMonths.filter((item) => item !== month) : [...selectedMonths, month], nextWeeks = !nextMonths.length || !data ? data?.meta.weeks ?? [] : [...new Set(nextMonths.flatMap((item) => data.meta.monthWeeks[item] ?? []))]; setSelectedMonths(nextMonths); setSelectedWeeks((current) => current.filter((week) => nextWeeks.includes(week))); }
  function toggleWeek(week: number) { setSelectedWeeks((current) => current.includes(week) ? current.filter((item) => item !== week) : [...current, week].sort((a, b) => a - b)); }
  function drillDown(item: Result) { if (view === "region") selectRegion(item.id); else if (view === "dm") selectDm(item.id); document.querySelector(".story-card-v2")?.scrollIntoView({ behavior: "smooth", block: "center" }); }
  function exportStem() { const clean = scopeLabel.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-zA-Z0-9]+/g, "").slice(0, 22) || "Nacional"; return `FHW_${clean}_${pluralView(view)}`; }
  function reportExport() { return { title: "FHW · Cada Taza Cuenta", scope: scopeLabel, period: `${periodLabel} · ${rangeLabel}`, level: scopeHeading, metric: metricLabel, score, movement: delta, coverage: coverageRatio, storyTitle, storyText, target: data?.meta.target ?? .1, rankingLimit: pdfLimit, results, trend }; }
  function requestExport(kind: ExportKind) { exportRef.current?.removeAttribute("open"); setExportComplete(null); setExportIntent(kind); }
  function dismissExport() { setExportIntent(null); setExportComplete(null); }
  function confirmExport() { if (exportIntent === "pdf") { setExportIntent(null); downloadDashboardPdf(reportExport(), `${exportStem()}.pdf`); setExportComplete("pdf"); } else if (exportIntent === "xlsx") { setExportIntent(null); downloadDashboardXlsx(reportExport(), `${exportStem()}.xlsx`); setExportComplete("xlsx"); } }

  if (error) return <main className="state-screen"><img src="assets/logo-cada-taza-cuenta.webp" alt="FHW"/><h1>No pudimos abrir el tablero</h1><p>{error}</p><button onClick={() => location.reload()}>Reintentar</button></main>;
  if (!data) return <main className="state-screen"><div className="loader"/><h1>Preparando Cada Taza Cuenta</h1><p>Cargando el tablero…</p></main>;
  const resource = resources.resources[0];

  return <div className="app-shell">
    <header className="topbar"><a className="brand" href="#inicio"><img src="assets/logo-cada-taza-cuenta.webp" alt="FHW"/><span><strong>FHW</strong><small>Cada Taza Cuenta</small></span></a></header>
    <main id="inicio">
      <section className="control-card"><div className="level-tabs" role="tablist" aria-label="Nivel de análisis">{LEVELS.map((item) => <button key={item} role="tab" aria-selected={view === item} className={view === item ? "active" : ""} onClick={() => changeLevel(item)}>{labelView(item)}</button>)}</div><div className="scope-controls"><label><span>Región</span><select value={region} onChange={(event) => selectRegion(event.target.value)}><option value="">Todas las regiones</option>{regionOptions.map((item) => <option key={item}>{item}</option>)}</select></label><label><span>DM</span><select value={dm} onChange={(event) => selectDm(event.target.value)} disabled={!region && view === "region"}><option value="">Todos los DMs</option>{dmOptions.map((item) => <option key={item} value={item}>{displayDm(item)}</option>)}</select></label><div className="period-filter"><span>Mes</span><details className="multi-select"><summary>{selectedMonths.length ? `${selectedMonths.length} ${selectedMonths.length === 1 ? "mes" : "meses"}` : "Todos los meses"}<svg viewBox="0 0 20 20" aria-hidden="true"><path d="m5 8 5 5 5-5"/></svg></summary><div className="multi-select-list"><button type="button" className={!selectedMonths.length ? "selected" : ""} onClick={() => setSelectedMonths([])}>Todos los meses</button>{data.meta.months.map((month) => <label key={month}><input type="checkbox" checked={selectedMonths.includes(month)} onChange={() => toggleMonth(month)}/><span>{month}</span></label>)}</div></details></div><div className="period-filter"><span>Semana</span><details className="multi-select"><summary>{selectedWeeks.length ? conciseRange(selectedWeeks) : "Todas las semanas"}<svg viewBox="0 0 20 20" aria-hidden="true"><path d="m5 8 5 5 5-5"/></svg></summary><div className="multi-select-list"><button type="button" className={!selectedWeeks.length ? "selected" : ""} onClick={() => setSelectedWeeks([])}>Todas las semanas</button>{availableWeeks.map((week) => <label key={week}><input type="checkbox" checked={selectedWeeks.includes(week)} onChange={() => toggleWeek(week)}/><span>Semana {week}</span></label>)}</div></details></div>{view === "store" && <label className="store-search"><span>Tienda</span><input value={storeSearch} onChange={(event) => setStoreSearch(event.target.value)} placeholder="Nombre o CeCo" aria-label="Buscar tienda por nombre o CeCo"/></label>}<details className="export-menu" ref={exportRef}><summary>Descargar <svg viewBox="0 0 20 20" aria-hidden="true"><path d="m5 8 5 5 5-5"/></svg></summary><div><button onClick={() => requestExport("pdf")}><strong>PDF ejecutivo</strong><span>Horizontal · 1 hoja</span></button><button onClick={() => requestExport("xlsx")}><strong>Excel | Dash</strong><span>Resumen, detalle y tendencia</span></button></div></details></div></section>
      <section className="overview-card"><div className="overview-title"><small>{scopeLabel}</small><h1>Cada Taza Cuenta</h1><p>{periodLabel} · {metricLabel}</p></div><ScoreRing value={score}/><div className="overview-facts"><span><small>Movimiento</small><strong className={delta !== null && delta >= 0 ? "positive" : ""}>{delta === null ? "—" : `${delta >= 0 ? "+" : ""}${pct.format(delta)}`}</strong><em>vs sem. anterior</em></span><span><small>Cobertura</small><strong>{coverageRatio === null ? "—" : pct.format(coverageRatio)}</strong></span><span><small>Tiendas &gt;10%</small><strong>{storeStatus.above} / {storeStatus.stores}</strong></span></div></section>
      <section className="story-card-v2"><span className={score !== null && score > .1 ? "story-signal good" : "story-signal"}/><div><small>AHORA</small><h2>{storyTitle}</h2><p>{storyText}</p></div><div className="story-split"><span><small>Líder</small><strong>{leader?.label ?? "—"}</strong><b>{leader ? pct.format(leader.ratio) : "—"}</b></span><span><small>Siguiente foco</small><strong>{priority?.label ?? "—"}</strong><b>{priority ? pct.format(priority.ratio) : "—"}</b></span></div></section>
      <section className="dashboard-grid"><article className="panel trend-panel"><div className="panel-head"><div><small>TENDENCIA · {periodLabel.toUpperCase()}</small><h2>{trendTitle}</h2></div><div className="chart-controls"><div className="toggle"><button className={trendPeriod === "week" ? "active" : ""} onClick={() => setTrendPeriod("week")}>Semana</button><button className={trendPeriod === "month" ? "active" : ""} onClick={() => setTrendPeriod("month")}>Mes</button></div></div></div><TrendChart points={trend} target={data.meta.target}/>{historyLoading && <span className="chart-note">Cargando tendencia…</span>}{historyError && <span className="chart-note error">{historyError}</span>}</article><article className="panel ranking-panel"><div className="panel-head"><div><small>PROMEDIO CTC · {pluralView(view).toUpperCase()}</small><h2>{rankingMode === "top" ? "Top desempeño" : "Bottom · oportunidad"}</h2></div><div className="toggle"><button className={rankingMode === "top" ? "active" : ""} onClick={() => setRankingMode("top")}>Top</button><button className={rankingMode === "bottom" ? "active" : ""} onClick={() => setRankingMode("bottom")}>Bottom</button></div></div>{ranked.length ? <Ranking items={ranked} onSelect={drillDown} compact={view !== "store"}/> : <div className="empty"><strong>Sin datos en el corte</strong><span>No hay información disponible.</span></div>}</article></section>
      {initiative && <section className="initiative-card"><div><small>{initiative.eyebrow}</small><h2>{initiative.title}</h2><p>{initiative.message}</p></div><span>{initiative.badge}</span></section>}
      <section className="review-card"><div><small>REVISIÓN EN TIENDA</small><h2>La experiencia también cuenta</h2><p>Una señal amable para abrir la conversación y mejorar en equipo.</p></div><video className="review-video" src="assets/fhw-revision.mp4" autoPlay muted loop playsInline preload="metadata" controls aria-label="Video de experiencia para consumo en lobby">Tu navegador no puede reproducir este video.</video></section>
      {resource && <section className="resource-card"><div className="resource-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 3h9l3 3v15H6V3Zm8 0v4h4M9 12h6M9 16h6"/></svg></div><div><small>{resource.category}</small><h2>{resource.title}</h2><p>{resource.description}</p></div><a className="button solid" href={resource.file} download>{resource.action}</a></section>}
    </main>
    <footer className="site-footer"><div className="footer-credits"><strong>FHW · Cada Taza Cuenta</strong><span>Diseñado por Jesus Alfredo Lopez Ramirez &amp; Enrique César Flores</span></div><div className="footer-legal"><span>Información propiedad de la marca. Prohibida su divulgación.</span><a href="https://wa.me/message/ENKDSAHYHIGAN1" target="_blank" rel="noreferrer">Comentarios y/o Sugerencias</a></div></footer>
    <ExportDialog kind={exportIntent} complete={exportComplete} onCancel={dismissExport} onConfirm={confirmExport}/>
  </div>;
}
