type ExportRow = { label:string; detail:string; ratio:number; stores:number };
type ExportTrend = { label:string; ratio:number; direct:boolean };

export type DashboardExport = {
  title:string;
  scope:string;
  period:string;
  level:string;
  metric:string;
  score:number|null;
  movement:number|null;
  coverage:number|null;
  storyTitle:string;
  storyText:string;
  target:number;
  results:ExportRow[];
  trend:ExportTrend[];
};

const encoder=new TextEncoder();
const xml=(value:string)=>value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const pct=(value:number|null)=>value===null?"—":new Intl.NumberFormat("es-MX",{style:"percent",minimumFractionDigits:1,maximumFractionDigits:1}).format(value);

function crc32(bytes:Uint8Array){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let bit=0;bit<8;bit++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return(crc^0xffffffff)>>>0;}
function u16(value:number){const bytes=new Uint8Array(2);new DataView(bytes.buffer).setUint16(0,value,true);return bytes;}
function u32(value:number){const bytes=new Uint8Array(4);new DataView(bytes.buffer).setUint32(0,value,true);return bytes;}
function join(parts:Uint8Array[]){const size=parts.reduce((sum,item)=>sum+item.length,0),result=new Uint8Array(size);let offset=0;for(const part of parts){result.set(part,offset);offset+=part.length;}return result;}

function zip(files:Array<{name:string;content:string}>){const local:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0;for(const file of files){const name=encoder.encode(file.name),data=encoder.encode(file.content),crc=crc32(data);const header=join([u32(0x04034b50),u16(20),u16(0x0800),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name]);local.push(header,data);central.push(join([u32(0x02014b50),u16(20),u16(20),u16(0x0800),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=header.length+data.length;}const centralBytes=join(central);return join([...local,centralBytes,u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(centralBytes.length),u32(offset),u16(0)]);}

function cell(ref:string,value:string|number|null,style=0){if(typeof value==="number")return`<c r="${ref}" s="${style}"><v>${value}</v></c>`;return`<c r="${ref}" s="${style}" t="inlineStr"><is><t>${xml(value??"")}</t></is></c>`;}
function row(index:number,cells:string[],height?:number){return`<row r="${index}"${height?` ht="${height}" customHeight="1"`:""}>${cells.join("")}</row>`;}
function sheet(rows:string[],merges:string[],widths:number[]){return`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0" showGridLines="0"/></sheetViews><sheetFormatPr defaultRowHeight="18"/><cols>${widths.map((width,index)=>`<col min="${index+1}" max="${index+1}" width="${width}" customWidth="1"/>`).join("")}</cols><sheetData>${rows.join("")}</sheetData>${merges.length?`<mergeCells count="${merges.length}">${merges.map((ref)=>`<mergeCell ref="${ref}"/>`).join("")}</mergeCells>`:""}<pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/><pageSetup orientation="landscape" paperSize="9" fitToWidth="1" fitToHeight="0"/></worksheet>`;}

function buildDashboard(report:DashboardExport){const results=[...report.results].sort((a,b)=>b.ratio-a.ratio),top=results.slice(0,10),bottom=[...results].reverse().slice(0,10),rows:string[]=[];rows.push(row(1,[cell("A1",report.title,1)],30),row(2,[cell("A2",`${report.level} · ${report.scope} · ${report.period}`,2)],23));rows.push(row(4,[cell("A4","RESULTADO",3),cell("C4","MOVIMIENTO",3),cell("E4","COBERTURA",3)]));rows.push(row(5,[cell("A5",pct(report.score),4),cell("C5",pct(report.movement),4),cell("E5",pct(report.coverage),4)],28));rows.push(row(7,[cell("A7",report.storyTitle,10)],24),row(8,[cell("A8",report.storyText,11)],34));rows.push(row(10,[cell("A10","TOP",5),cell("B10",report.metric,5),cell("D10","BOTTOM",5),cell("E10",report.metric,5)]));for(let i=0;i<10;i++){const left=top[i],right=bottom[i],r=11+i;rows.push(row(r,[cell(`A${r}`,left?.label??"",6),cell(`B${r}`,left?left.ratio:null,7),cell(`D${r}`,right?.label??"",6),cell(`E${r}`,right?right.ratio:null,7)]));}rows.push(row(22,[cell("A22","TENDENCIA",10)],24),row(23,[cell("A23","Periodo",5),cell("B23",report.metric,5),cell("C23","Fuente",5)]));report.trend.forEach((item,index)=>{const r=24+index;rows.push(row(r,[cell(`A${r}`,item.label,6),cell(`B${r}`,item.ratio,7),cell(`C${r}`,item.direct?"Dato histórico":"Dato calculado",6)]));});return sheet(rows,["A1:F1","A2:F2","A7:F7","A8:F8","A22:F22"],[29,15,4,29,15,4]);}

function buildDetail(report:DashboardExport){const rows=[row(1,[cell("A1",`Detalle · ${report.level}`,1)],30),row(2,[cell("A2",`${report.scope} · ${report.period}`,2)],23),row(4,[cell("A4","Nombre",5),cell("B4","Alcance",5),cell("C4",report.metric,5),cell("D4","Estado",5)])];[...report.results].sort((a,b)=>b.ratio-a.ratio).forEach((item,index)=>{const r=5+index;rows.push(row(r,[cell(`A${r}`,item.label,6),cell(`B${r}`,item.detail,6),cell(`C${r}`,item.ratio,7),cell(`D${r}`,item.ratio>report.target?"Sobre meta":"Oportunidad",item.ratio>report.target?8:9)]));});return sheet(rows,["A1:D1","A2:D2"],[31,42,18,18]);}

export function createDashboardXlsx(report:DashboardExport){const files=[
  {name:"[Content_Types].xml",content:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/></Types>'},
  {name:"_rels/.rels",content:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>'},
  {name:"xl/workbook.xml",content:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><bookViews><workbookView/></bookViews><sheets><sheet name="Dashboard" sheetId="1" r:id="rId1"/><sheet name="Detalle" sheetId="2" r:id="rId2"/></sheets><calcPr calcId="191029"/></workbook>'},
  {name:"xl/_rels/workbook.xml.rels",content:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'},
  {name:"xl/styles.xml",content:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="5"><font><sz val="10"/><name val="Aptos"/><color rgb="FF17231E"/></font><font><b/><sz val="22"/><name val="Aptos Display"/><color rgb="FFFFFFFF"/></font><font><b/><sz val="10"/><name val="Aptos"/><color rgb="FF006241"/></font><font><b/><sz val="9"/><name val="Aptos"/><color rgb="FFFFFFFF"/></font><font><b/><sz val="16"/><name val="Aptos Display"/><color rgb="FF17231E"/></font></fonts><fills count="6"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF006241"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFE8F3EE"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFF8EAE7"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFF4F8F6"/></patternFill></fill></fills><borders count="2"><border/><border><left style="thin"><color rgb="FFD7E1DC"/></left><right style="thin"><color rgb="FFD7E1DC"/></right><top style="thin"><color rgb="FFD7E1DC"/></top><bottom style="thin"><color rgb="FFD7E1DC"/></bottom></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="12"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="2" fillId="3" borderId="0" xfId="0"/><xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="4" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="3" fillId="2" borderId="1" xfId="0"/><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyAlignment="1"><alignment vertical="center"/></xf><xf numFmtId="10" fontId="2" fillId="0" borderId="1" xfId="0"/><xf numFmtId="0" fontId="2" fillId="3" borderId="1" xfId="0"/><xf numFmtId="0" fontId="2" fillId="4" borderId="1" xfId="0"/><xf numFmtId="0" fontId="2" fillId="5" borderId="0" xfId="0"/><xf numFmtId="0" fontId="0" fillId="5" borderId="0" xfId="0" applyAlignment="1"><alignment wrapText="1" vertical="top"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>'},
  {name:"xl/worksheets/sheet1.xml",content:buildDashboard(report)},
  {name:"xl/worksheets/sheet2.xml",content:buildDetail(report)},
  {name:"docProps/core.xml",content:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:title>${xml(report.title)}</dc:title><dc:creator>FHW · Cada Taza Cuenta</dc:creator><dcterms:created xsi:type="dcterms:W3CDTF">${new Date().toISOString()}</dcterms:created></cp:coreProperties>`},
  {name:"docProps/app.xml",content:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"><Application>FHW · Cada Taza Cuenta</Application></Properties>'},
  ];return new Blob([zip(files)],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});
}

export function downloadDashboardXlsx(report:DashboardExport,filename:string){const url=URL.createObjectURL(createDashboardXlsx(report)),anchor=document.createElement("a");anchor.href=url;anchor.download=filename;document.body.append(anchor);anchor.click();anchor.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1500);}
